format_version: v1.0
configName: cec1736_evb
folderName: cec1736_evb
frameworkPath: C:\h3
processor: CEC1736_S0_2ZW
projectName: cec1736_evb
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\CEC_DFP\1.7.151\cec1736\atdf\CEC1736_S0_2ZW.atdf
